name: Laravel Tests

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306
        # Wait until MySQL is ready
        healthcheck:
          test: ["CMD-SHELL", "mysqladmin ping --silent"]
          interval: 10s
          timeout: 5s
          retries: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: mbstring, intl, bcmath, mysql
          ini-values: post_max_size=256M, max_execution_time=300

      - name: Install dependencies
        run: |
          composer install
          cp .env.example .env
          php artisan key:generate

      - name: Configure Laravel to use in-memory SQLite
        run: |
          sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=sqlite/g' .env
          touch database/database.sqlite

      - name: Run migrations
        run: |
          php artisan migrate

      - name: Run tests
        run: |
          vendor/bin/phpunit --coverage-text
